# Generated by Django 4.0.6 on 2022-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faredata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('service_charge', models.IntegerField()),
                ('surge_charge', models.IntegerField()),
                ('initial_fare', models.IntegerField()),
                ('km_rate', models.IntegerField()),
            ],
        ),
    ]
